version: '2.14'
services:
  buildgrace:
    build: .
    volumes:
      - builtfiles:/godotapp/Exports/web/
    environment:
      - GODOT_VERSION="3.5.1"
  web:
    image: nginx
    depends_on:
      - buildgrace
    volumes:
    - builtfiles:/var/www/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:80"
    environment:
      - NGINX_LOCATION="/"

volumes:
  builtfiles: