name: Compile for web
on:
  push:
    branches:
      - main
      
jobs:
  Export-to-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Compile project web with godot
        run:  godot --path ${GITHUB_WORKSPACE} --export "HTML5"

      - name: test
        run: ls ${GITHUB_WORKSPACE}
