name: Compile for web
on:
  push:
    branches:
      - master
      
jobs:
  Export-to-web:
    runs-on: ubuntu-latest
    steps:
      - run: apt update && apt upgrade

      - name: install godot
        run: wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_linux_headless.64.zip \
            && unzip Godot_v3.5.1-stable_linux_headless.64.zip \
            && mv Godot_v3.5.1-stable_linux_headless.64 /usr/bin/godot \
            && rm Godot_v3.5.1-stable_linux_headless.64.zip
      
      - name: install godot export templates
        run: wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz \
            && unzip Godot_v3.5.1-stable_export_templates.tpz \
            && mkdir -p /root/.local/share/godot/templates/ \
            && cp -r templates/* /root/.local/share/godot/templates/3.5.1/
      
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Compile project web with godot
        run:  godot --path ${GITHUB_WORKSPACE} --export "HTML5"

      - name: test
        run: ls ${GITHUB_WORKSPACE}
